import { OnchainWallet, SingleKey } from "@arkade-os/sdk";
import { HDKey } from "@bitcoinerlab/descriptors-scure";
import { bech32m, hex } from "@scure/base";
import { mnemonicToSeedSync } from "@scure/bip39";
import { NETWORK, p2tr } from "@scure/btc-signer";

const ALICE_SEED =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" as const;

/** 1. Convert mnemonic phrase into 64 byte seed */
console.log("Converting mnemonic phrase to seed...");
const aliceSeed = mnemonicToSeedSync(ALICE_SEED);

/** 2. Derive BIP32 master node from seed */
console.log("Deriving master node from seed...");
const masterNode = HDKey.fromMasterSeed(aliceSeed);

/** 3. Derive BIP32 account node from master
 * - Purpose: Taproot (BIP86), hardened (indicated by the apostrophe)
 * - Coin type: Mainnet (indicated by '0'), hardened
 * - Account: 0 (first account), hardened
 * - Change index: 0 (for receiving funds from external addresses), non-hardened
 * - Address index: 0 (first address), non-hardened
 */
console.log("Deriving account node from master...");
const accountNode = masterNode.derive("m/86'/0'/0'/0/0");

/** 4. Extract 32-byte x-only public key by slicing off the prefix */
const pubKey = accountNode.publicKey!.slice(1);
console.log("Extracted public key:", [hex.encode(pubKey)]);

/** 5. Generate standard tapscript */
console.log("Generating standard tapscript...");
const standardTapscript = p2tr(
  pubKey, // internal public key (keypath spend)
  undefined, // taproot tree (empty)
  NETWORK, // bitcoin mainnet
);

/** 6. Encode standard tapscript as bech32m address */
const coder = bech32m; // Encoder to use (bech32m, used by Taproot)
const version = 1; // Witness version 1 (Taproot)
const words = coder.toWords(standardTapscript.tweakedPubkey); // "Words" in this context means a 5-bit chunk
const address = coder.encode(NETWORK.bech32, [version].concat(words));
console.log("Encoded standard address at path m/86'/0'/0'/0/0:", [address]);

/** 7. Validate against Arkade SDK helper */
const onchainWallet = await OnchainWallet.create(
  SingleKey.fromPrivateKey(accountNode.privateKey!),
  "bitcoin",
);
console.log("Matches address generated by Arkade SDK helper?", [
  onchainWallet.address === address,
]);
