import {
  ArkAddress,
  CSVMultisigTapscript,
  InMemoryContractRepository,
  InMemoryWalletRepository,
  MultisigTapscript,
  RestArkProvider,
  RestDelegatorProvider,
  SingleKey,
  VtxoScript,
  Wallet,
} from "@arkade-os/sdk";
import { HDKey } from "@bitcoinerlab/descriptors-scure";
import { hex } from "@scure/base";
import { mnemonicToSeedSync } from "@scure/bip39";

// Temporary polyfill to enable calling `wallet.getContractManager()`
import { EventSource } from "eventsource";
globalThis.EventSource ??= EventSource as never;

const ALICE_SEED =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" as const;
const OPERATOR_URL = "https://arkade.computer" as const;
const DELEGATE_URL = "https://delegate.arkade.money" as const;

/** 1. Convert mnemonic phrase into 64 byte seed */
console.log("Converting mnemonic phrase to seed...");
const aliceSeed = mnemonicToSeedSync(ALICE_SEED);

/** 2. Derive BIP32 master node from seed */
console.log("Deriving master node from seed...");
const masterNode = HDKey.fromMasterSeed(aliceSeed);

/** 3. Derive BIP32 account node from master
 * - Purpose: Taproot (BIP86), hardened (indicated by the apostrophe)
 * - Coin type: Mainnet (indicated by '0'), hardened
 * - Account: 0 (first account), hardened
 * - Change index: 0 (for receiving funds from external addresses), non-hardened
 * - Address index: 0 (first address), non-hardened
 */
console.log("Deriving account node from master...");
const accountNode = masterNode.derive("m/86'/0'/0'/0/0");

/** 4. Extract 32-byte x-only public key by slicing off the prefix */
const userPubkey = accountNode.publicKey!.slice(1);
console.log("Extracted user public key:", [hex.encode(userPubkey)]);

/** 5. Fetch Arkade operator info */
console.log("Connecting to Arkade operator...");
const operator = new RestArkProvider(OPERATOR_URL);
const operatorInfo = await operator.getInfo();

/** 6. Extract operator public key */
const operatorPubkey = hex.decode(operatorInfo.signerPubkey).slice(1);
console.log("Extracted operator public key:", [hex.encode(operatorPubkey)]);

/** 7. Generate default tapscript */
console.log("Generating default tapscript...");
const defaultPaths = [
  // forfeit (collaborative spend with operator)
  MultisigTapscript.encode({
    pubkeys: [userPubkey, operatorPubkey],
  }).script,
  // unilateral exit with timelock
  CSVMultisigTapscript.encode({
    timelock: {
      value: operatorInfo.unilateralExitDelay,
      type: "seconds",
    },
    pubkeys: [userPubkey],
  }).script,
];
const defaultTapscript = new VtxoScript(defaultPaths);

/** 8. Encode default tapscript as Arkade address */
const defaultAddress = new ArkAddress(
  operatorPubkey,
  defaultTapscript.tweakedPublicKey,
  "ark",
).encode();
console.log("Generated default Arkade address:", [defaultAddress]);

/** 9. Fetch delegate info */
console.log("Connecting to delegate...");
const delegate = new RestDelegatorProvider(DELEGATE_URL);
const delegateInfo = await delegate.getDelegateInfo();

/** 10. Extract delegate public key */
const delegatePubkey = hex.decode(delegateInfo.pubkey).slice(1);
console.log("Extracted delegate public key:", [hex.encode(delegatePubkey)]);

/** 11. Generate delegate tapscript */
const delegateTapscript = new VtxoScript([
  ...defaultPaths,
  MultisigTapscript.encode({
    pubkeys: [userPubkey, delegatePubkey, operatorPubkey],
  }).script,
]);

/** 12. Encode delegate tapscript as Arkade address */
const delegatedAddress = new ArkAddress(
  operatorPubkey,
  delegateTapscript.tweakedPublicKey,
  "ark",
).encode();
console.log("Generated delegated Arkade address:", [delegatedAddress]);

/** 13. Validate against Arkade SDK helper */
const wallet = await Wallet.create({
  identity: SingleKey.fromPrivateKey(accountNode.privateKey!),
  arkProvider: operator,
  delegatorProvider: delegate,
  settlementConfig: false, // Don't auto-renew VTXOs
  storage: {
    // node doesn't have indexedDB, so we have to specify in-memory repos here
    walletRepository: new InMemoryWalletRepository(),
    contractRepository: new InMemoryContractRepository(),
  },
});

// Temporary workaround to return both address types in non-browser environments
await wallet
  .getContractManager()
  .then((manager) => manager.getContracts())
  .then((contracts) => {
    for (const contract of contracts) {
      if (contract.type === "default") {
        console.log(
          "Default address matches address generated by Arkade SDK helper?",
          [defaultAddress === contract.address],
        );
      }
      if (contract.type === "delegate") {
        console.log(
          "Delegated address matches address generated by Arkade SDK helper?",
          [delegatedAddress === contract.address],
        );
      }
    }
  });
await wallet.dispose();
