use bip39::Mnemonic;
use bitcoin::bip32::{DerivationPath, Xpriv};
use bitcoin::key::{Keypair, Secp256k1};
use bitcoin::{Address, Network, XOnlyPublicKey};
use std::str::FromStr;

const ALICE_SEED: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

fn main() -> anyhow::Result<()> {
    // Initialize secp256k1 for cryptographic operations
    let secp = Secp256k1::new();

    /* 1. Convert mnemonic phrase into 64 byte seed */
    println!("Converting mnemonic phrase to seed...");
    let mnemonic = Mnemonic::parse_normalized(ALICE_SEED).expect("Failed to parse mnemonic");
    let alice_seed = mnemonic.to_seed("");

    /* 2. Derive BIP32 master node from seed */
    println!("Deriving master node from seed...");
    let master_node = Xpriv::new_master(Network::Bitcoin, &alice_seed)?;

    /* 3. Derive BIP32 account node from master
     * - Purpose: Taproot (BIP86), hardened (indicated by the apostrophe)
     * - Coin type: Mainnet (indicated by '0'), hardened
     * - Account: 0 (first account), hardened
     * - Change index: 0 (for receiving funds from external addresses), non-hardened
     * - Address index: 0 (first address), non-hardened
     */
    println!("Deriving account node from master...");
    let derivation_path = DerivationPath::from_str("m/86'/0'/0'/0/0")?;
    let account_node = master_node.derive_priv(&secp, &derivation_path)?;

    /* 4. Extract 32-byte x-only public key by slicing off the prefix */
    // The `bitcoin` crate handles the 33-byte to 32-byte X-Only conversion automatically
    // when we convert a Keypair into an XOnlyPublicKey
    let keypair = Keypair::from_secret_key(&secp, &account_node.private_key);
    let (pub_key, _parity) = XOnlyPublicKey::from_keypair(&keypair);
    println!(
        "Extracted public key: [\"{}\"]",
        hex::encode(pub_key.serialize())
    );

    /* 5. Generate standard tapscript */
    println!("Generating standard tapscript...");
    // standard Taproot generation (keypath spend with no script tree)
    // is bundled directly into the Address encoding function.

    /* 6. Encode standard tapscript as bech32m address */
    let address = Address::p2tr(&secp, pub_key, None, Network::Bitcoin);
    println!(
        "Encoded standard address at path m/86'/0'/0'/0/0: [\"{}\"]",
        address.to_string()
    );

    /* 7. Validate against bitcoin::Address crate */
    let expected_p2tr_address = Address::p2tr(&secp, pub_key, None, Network::Bitcoin);
    println!(
        "Matches address generated by helper? [{}]",
        address == expected_p2tr_address
    );

    Ok(())
}
