use bdk_wallet::{KeychainKind, Wallet, template::Bip84};
use bip39::Mnemonic;
use bitcoin::{
    Address, Network,
    bip32::{DerivationPath, Xpriv, Xpub},
    key::{CompressedPublicKey, Secp256k1},
};
use std::str::FromStr;

const ALICE_MNEMONIC: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

fn main() -> anyhow::Result<()> {
    /* 1. Convert mnemonic phrase into 64 byte seed */
    println!("Converting mnemonic phrase to seed...");
    let mnemonic: Mnemonic = ALICE_MNEMONIC.parse()?;
    let seed = mnemonic.to_seed("");

    let secp = Secp256k1::new();

    /* 2. Derive BIP32 master node from seed */
    println!("Deriving master node from seed...");
    let master_xpriv = Xpriv::new_master(Network::Bitcoin, &seed)?;

    /* 3. Derive BIP32 account node from master
     * - Purpose: Native SegWit (BIP84), hardened (indicated by the apostrophe)
     * - Coin type: Mainnet (indicated by '0'), hardened
     * - Account: 0 (first account), hardened
     * - Change index: 0 (for receiving funds from external addresses), non-hardened
     * - Address index: 0 (first address), non-hardened
     */
    println!("Deriving account node from master...");
    let leaf_path = DerivationPath::from_str("m/84'/0'/0'/0/0")?;
    let leaf_xpriv = master_xpriv.derive_priv(&secp, &leaf_path)?;

    /* 4. Extract 33-byte compressed public key */
    let xpub = Xpub::from_priv(&secp, &leaf_xpriv);
    let pub_key = CompressedPublicKey(xpub.public_key);
    println!(
        "Extracted public key: ['{}']",
        hex::encode(pub_key.0.serialize())
    );

    /* 5. Generate standard p2wpkh script (Native SegWit) */
    println!("Generating standard p2wpkh script...");
    let standard_address = Address::p2wpkh(&pub_key, Network::Bitcoin);

    /* 6. Encode p2wpkh as bech32 address */
    println!(
        "Encoded standard address at path m/84'/0'/0'/0/0: ['{}']",
        standard_address
    );

    /* 7. Validate against ark-bdk-wallet */
    let ark_wallet = Wallet::create(
        Bip84(master_xpriv, KeychainKind::External),
        Bip84(master_xpriv, KeychainKind::Internal),
    )
    .network(Network::Bitcoin)
    .create_wallet_no_persist()?;

    let sdk_address = ark_wallet.peek_address(KeychainKind::External, 0).address;
    println!(
        "Matches address generated by ark-bdk-wallet? [{}]",
        standard_address.to_string() == sdk_address.to_string()
    );

    Ok(())
}
