import {
  CSVMultisigTapscript,
  InMemoryContractRepository,
  InMemoryWalletRepository,
  MultisigTapscript,
  RestArkProvider,
  SingleKey,
  VtxoScript,
  Wallet,
} from "@arkade-os/sdk";
import { HDKey } from "@bitcoinerlab/descriptors-scure";
import { bech32m, hex } from "@scure/base";
import { mnemonicToSeedSync } from "@scure/bip39";
import { NETWORK } from "@scure/btc-signer";

const ALICE_SEED =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" as const;
const OPERATOR_URL = "https://arkade.computer" as const;

/** 1. Convert mnemonic phrase into 64 byte seed */
console.log("Converting mnemonic phrase to seed...");
const aliceSeed = mnemonicToSeedSync(ALICE_SEED);

/** 2. Derive BIP32 master node from seed */
console.log("Deriving master node from seed...");
const masterNode = HDKey.fromMasterSeed(aliceSeed);

/** 3. Derive BIP32 account node from master
 * - Purpose: Taproot (BIP86), hardened (indicated by the apostrophe)
 * - Coin type: Mainnet (indicated by '0'), hardened
 * - Account: 0 (first account), hardened
 * - Change index: 0 (for receiving funds from external addresses), non-hardened
 * - Address index: 0 (first address), non-hardened
 */
console.log("Deriving account node from master...");
const accountNode = masterNode.derive("m/86'/0'/0'/0/0");

/** 4. Extract 32-byte x-only public key by slicing off the prefix */
const userPubkey = accountNode.publicKey!.slice(1);
console.log("Extracted user public key:", [hex.encode(userPubkey)]);

/** 5. Fetch Arkade operator info */
console.log("Connecting to Arkade operator...");
const operator = new RestArkProvider(OPERATOR_URL);
const operatorInfo = await operator.getInfo();

/** 6. Extract operator public key */
const operatorPubkey = hex.decode(operatorInfo.signerPubkey).slice(1);
console.log("Extracted operator public key:", [hex.encode(operatorPubkey)]);

/** 7. Generate boarding tapscript */
console.log("Generating boarding tapscript...");
const boardingTapscript = new VtxoScript([
  // forfeit (collaborative spend with operator)
  MultisigTapscript.encode({
    pubkeys: [userPubkey, operatorPubkey],
  }).script,
  // unilateral exit with timelock
  CSVMultisigTapscript.encode({
    timelock: {
      value: operatorInfo.boardingExitDelay,
      type: "seconds",
    },
    pubkeys: [userPubkey],
  }).script,
]);

/** 8. Encode boarding tapscript as bech32m address */
const coder = bech32m; // Encoder to use (bech32m, used by Taproot)
const version = 1; // Witness version 1 (Taproot)
const words = coder.toWords(boardingTapscript.tweakedPublicKey); // "Words" in this context means a 5-bit chunks
const address = bech32m.encode(NETWORK.bech32, [version].concat(words));
console.log("Generated Arkade boarding address:", [address]);

/** 9. Validate against Arkade SDK helper */
const wallet = await Wallet.create({
  identity: SingleKey.fromPrivateKey(accountNode.privateKey!),
  arkProvider: operator,
  settlementConfig: false, // Don't auto-renew VTXOs
  storage: {
    // node doesn't have indexedDB, so we have to specify in-memory repos here
    walletRepository: new InMemoryWalletRepository(),
    contractRepository: new InMemoryContractRepository(),
  },
});
console.log("Matches address generated by Arkade SDK helper?", [
  (await wallet.getBoardingAddress()) === address,
]);
