use ark_core::script::{csv_sig_script, multisig_script, tr_script_pubkey};
use ark_core::{BoardingOutput, UNSPENDABLE_KEY};
use ark_rest::Client;
use bip39::Mnemonic;
use bitcoin::{
    bip32::{DerivationPath, Xpriv, Xpub},
    key::{PublicKey, Secp256k1},
    taproot::TaprootBuilder,
    Address, Network,
};
use std::str::FromStr;

const ALICE_MNEMONIC: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const ARK_SERVER_URL: &str = "https://arkade.computer";

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    /* 1. Convert mnemonic phrase into 64 byte seed */
    println!("Converting mnemonic phrase to seed...");
    let mnemonic: Mnemonic = ALICE_MNEMONIC.parse()?;
    let seed = mnemonic.to_seed("");

    let secp = Secp256k1::new();

    /* 2. Derive BIP32 master node from seed */
    println!("Deriving master node from seed...");
    let master_xpriv = Xpriv::new_master(Network::Bitcoin, &seed)?;

    /* 3. Derive BIP32 account node from master
     * - Purpose: Taproot (BIP86), hardened (indicated by the apostrophe)
     * - Coin type: Mainnet (indicated by '0'), hardened
     * - Account: 0 (first account), hardened
     * - Change index: 0 (for receiving funds from external addresses), non-hardened
     * - Address index: 0 (first address), non-hardened
     */
    println!("Deriving account node from master...");
    let path = DerivationPath::from_str("m/86'/0'/0'/0/0")?;
    let child_xpriv = master_xpriv.derive_priv(&secp, &path)?;

    /* 4. Extract 32-byte x-only public key */
    let xpub = Xpub::from_priv(&secp, &child_xpriv);
    let user_xonly = xpub.public_key.x_only_public_key().0;
    println!(
        "Extracted user public key: ['{}']",
        hex::encode(user_xonly.serialize())
    );

    /* 5. Fetch Arkade operator info */
    println!("Connecting to Arkade operator...");
    let client = Client::new(ARK_SERVER_URL.to_string())?;
    let server_info = client.get_info().await?;

    /* 6. Extract operator public key */
    let (server_xonly, _) = server_info.signer_pk.x_only_public_key();
    println!(
        "Extracted operator public key: ['{}']",
        hex::encode(server_xonly.serialize())
    );

    /* 7. Generate boarding tapscript */
    println!("Generating boarding tapscript...");
    let unspendable_key: PublicKey = UNSPENDABLE_KEY.parse()?;
    let (unspendable_xonly, _) = unspendable_key.inner.x_only_public_key();

    let forfeit_script = multisig_script(server_xonly, user_xonly);
    let exit_script = csv_sig_script(server_info.boarding_exit_delay, user_xonly);

    let mut builder = TaprootBuilder::new();
    builder = builder
        .add_leaf(1, forfeit_script)
        .map_err(|e| anyhow::anyhow!("invalid forfeit leaf: {e}"))?;
    builder = builder
        .add_leaf(1, exit_script)
        .map_err(|e| anyhow::anyhow!("invalid exit leaf: {e}"))?;
    let spend_info = builder
        .finalize(&secp, unspendable_xonly)
        .map_err(|_| anyhow::anyhow!("failed to finalize taproot builder"))?;

    /* 8. Encode boarding tapscript as bech32m address */
    let script_pubkey = tr_script_pubkey(&spend_info);
    let address = Address::from_script(&script_pubkey, Network::Bitcoin)?;
    println!("Generated Arkade boarding address: ['{}']", address);

    /* 9. Validate against Arkade SDK helper */
    let boarding_output = BoardingOutput::new(
        &secp,
        server_xonly,
        user_xonly,
        server_info.boarding_exit_delay,
        Network::Bitcoin,
    )?;
    println!(
        "Matches address generated by Arkade SDK helper? [{}]",
        address.to_string() == boarding_output.address().to_string()
    );

    Ok(())
}
